/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef CodeRunner_CONSTANTS_H
#define CodeRunner_CONSTANTS_H

#include "CodeRunner_types.h"



class CodeRunnerConstants {
 public:
  CodeRunnerConstants();

};

extern const CodeRunnerConstants g_CodeRunner_constants;



#endif
