/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "CodeRunner_constants.h"



const CodeRunnerConstants g_CodeRunner_constants;

CodeRunnerConstants::CodeRunnerConstants() {
}



